using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EnemyVariant
{
    SLIME_RED,
    SLIME_GREEN,
    SLIME_YELLOW,
    TURTLE_BLUE,
    TURTLE_BLACK,
    TURTLE_WHITE,
    MUMMY_GREY,
    MUMMY_WHITE,
    MUMMY_RED,
    LICH_PURPLE,
    LICH_GREEN,
    LICH_RED,
    GOLEM_GREEN,
    GOLEM_RED,
    GOLEM_RED2,
    BEHOLDER_PURPLE,
    BEHOLDER_CYAN,
    BEHOLDER_GREEN,
    BAT_PURPLE,
    SMALLDRAGON_RED,
    MONSTERPLANT_GREEN,
    ORC_GREEN,
    SKELETON_PURPLE,
    SPIDER_GREEN,
    EVILMAGE_PURPLE,
    ROBOGOLEM_GRAY,
    BOSS1,
    BOSS2,
    BOSS3,
    BOSS4

}
